name: Smallsemi
version: "0.7.1"
license: "GPL-3.0-or-later"
date: 2024-08-27
description: |
    A library of small semigroups

authors:
    - name: Andreas Distler
      url: mailto:a.distler@tu-bs.de
    - name: James Mitchell
      url: https://jdbm.me

maintainers:
    - name: James Mitchell
      url: https://jdbm.me

GAP: ">=4.10"

www: https://gap-packages.github.io/smallsemi/
readme: README
packageinfo: https://gap-packages.github.io/smallsemi/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/smallsemi/releases/download/v0.7.1/smallsemi-0.7.1.tar.gz

abstract: |
    The <Package>Smallsemi</Package> package is a data library of semigroups    of small size. It provides all semigroups with at most 8 elements as well    as various information about these objects.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    small semigroups, data library, multiplication tables.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>DM24</span>]   <b class='BibAuthor'>Distler, A. and Mitchell, J.</b>,
     <i class='BibTitle'>Smallsemi, A library of small semigroups,
             Version 0.7.1</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/smallsemi/">https://gap-packages.github.io/smallsemi/</a></span>.
    </p>
    

bibtex: |
    @misc{ Smallsemi,
      author =           {Distler, A. and Mitchell, J.},
      title =            {{Smallsemi},  A library of small semigroups, {V}ersion
                          0.7.1},
      month =            {Aug},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href      {https://gap-packages.github.io/smallsemi/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{smallsemi/}}},
      keywords =         {small semigroups; data library; multiplication tables},
      printedkey =       {DM24}
    }

